# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'HCWePoems' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HCWePoems
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'Kingfisher'
  pod 'SnapKit'
end

flutter_application_path = '../poem_detail_flutter'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
